<?php

namespace AppBundle\Repository;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFriendshipRequest($user)
    {
        $friendships_requests = $this->findBy(array("friend"=>$user, "isAccepted"=>null));
        return $friendships_requests;
    }

    public function getFriends($user)
    {
        $friends = $this->findBy(array("friend"=>$user, "isAccepted"=>true));
        return $friends;
    }

}
